### ISSUE TITLE
Issue Running Balena-Nextcloud on Banana Pi M1: Version Conflict Error

### ISSUE THREAD

**Issue by n1md4** [klutchell/balena-nextcloud#122]
I am encountering an issue while attempting to run the Balena-Nextcloud project on a Banana Pi M1. The specific error message I'm receiving states:
```
 nextcloud  Can't start Nextcloud because the version of the data (0.0.0.0) is higher than the docker image version (
 nextcloud  Warning: Invalid "upload_max_filesize" setting. Invalid quantity "2G": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
 nextcloud  
 nextcloud  Warning: Invalid "post_max_size" setting. Invalid quantity "2G": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
 nextcloud  26.0.5.1) and downgrading is not supported. Are you sure you have pulled the newest image version?
```

This error is preventing me from successfully launching Nextcloud on the Banana Pi M1.

**Hardware Specifications**

**Board**: Banana Pi M1 arm32v7

**Versions**

**Balena-Nextcloud Version**: 23.0.0-1640649026537
**Nextcloud Version**: 22.1.1 (assumed)
**Docker Image Version**: 27.0.2-fpm

Thank you for your assistance in resolving this issue. I look forward to your guidance on how to resolve this version conflict error and successfully run Balena-Nextcloud on my Banana Pi M1.

**Comment by klutchell** [comment]
Hey @n1md4, can you try setting a new environment variable `PHP_UPLOAD_LIMIT` to an empty value in your balena fleet dashboard? It seems your container does not agree with the 2G default value I provided in the compose file.

**Comment by n1md4** [comment]
Thanks.  The container is now starting correctly, but there are various timeouts and subsequent errors.  At this point I'm convinced the issue is a resource limit on the BPI.
