### ISSUE TITLE
http://nextcloud.local/ >> 404 Not Found

### ISSUE THREAD

**Issue by robertreid** [klutchell/balena-nextcloud#21]
When I go to http://nextcloud.local/ all that returns is:

404 Not Found
nginx/1.21.4

**Comment by klutchell** [comment]
May I ask how you deployed this project? Was it from the public fleet on balenaHub or did you deploy the fleet to your own account? Are you able to see the device in your dashboard?

**Comment by robertreid** [comment]
I tried it both way: one-click-deploy button > download image ... and also tried manual deployment through my balena account.  Same result both ways.  I can see that the device is running and creating log entries, but when I try to open the device page with my browser, it serves up the 404 Not Found page, nothing else.

**Comment by klutchell** [comment]
Okay, so it sounds like the nginx web server is running but the Nextcloud files are not present or the service isn't running.

- What type of device is this?
- Do all the services appear as `Running` in the services pane? Except `hostname`, that one should show `Exited`.
- Can you share some logs from the `nextcloud` service in your balena dashboard?
- Do you get a different response by connecting to the local device IP directly?
- Or by enabling the public URL (temporarily) and connecting to that? I expect the result will be the same but it's a good test.

**Comment by robertreid** [comment]
- Raspberry Pi 4 (using 64bit OS)
- Yes, mariadb, nextcloud, nginx, redis are all running; hostname is exited
- Logs attached
- Same response (404 Not Found) when connecting to either http://nextcloud.local/ or my http://10.0.1.49/ or https://redacted.balena-devices.com/

[balena-nextcloud_dry-water-13.11.21_15_03_24_(-0600).txt](https://github.com/klutchell/balena-nextcloud/files/7532756/balena-nextcloud_dry-water-13.11.21_15_03_24_.-0600.txt)

**Comment by klutchell** [comment]
Thanks again for raising this, I was able to reproduce the issue and I'm testing the fix now.

Can you set `NEXTCLOUD_UPDATE=1` as an env var in your dashboard in the meantime? This should fix the issue.

**Comment by robertreid** [comment]
Works.  Thanks!
