### ISSUE TITLE
Collabora Online - Built-in CODE Server (ARM64)	6.4.203 will not install

### ISSUE THREAD

**Issue by tbarnes8** [klutchell/balena-nextcloud#3]
![Collabora Online - Built-in CODE Server ARM64 6 4 203](https://user-images.githubusercontent.com/54909433/103182409-e706af00-485f-11eb-92cc-7180f15c0f90.PNG)

Error in photo is all it does. Goes back to Download and enable status.

**Comment by klutchell** [comment]
You may need to contact the author of that specific app as I'm not familiar with it.

https://apps.nextcloud.com/apps/richdocumentscode

Have you verified that you are running on an `arm64/aarch64` device (not `armv6hf` or `armv7hf`)? Running `uname -a` in your dashboard terminal will confirm.

**Comment by tbarnes8** [comment]
Looks like I am running aarch64
Linux 66bdd14 5.4.58 #1 SMP PREEMPT Wed Dec 16 14:42:39 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by tbarnes8** [comment]
I was able to install on a separate Ubuntu image successfully. I will check with the vendor, it is a big reason people would use this app. Thank you
