### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [klutchell/balena-nextcloud#343]
How can I add support for HTTPS using the docker compose in this repo?

**Comment by klutchell** [comment]
The simplest for this project is just to enable the [Public URL](https://docs.balena.io/learn/manage/actions/#public-device-url) feature in the balenaCloud dashboard.

If you want to use your own custom domain name and proxy service, I would suggest following examples like [this](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm).

**Comment by 0xAdriaTorralba** [comment]
I tried the public URL, but it is extremelly slow... so this solution is not practical.

I tried to setup a "regular" Nextcloud installation using Docker Compose but I didn't managed to run it...

So, I left Balena software altogether and started a "regular" Docker Compose installation (with Caddy) and it worked fine :)
